### ISSUE TITLE
config file entry for context files

### ISSUE THREAD

**Issue by fils** [fils/nabu#20]
Need to make a config file entry for the context file maps.  This is already done in Gleaner so I need to bring over the same approach to Nabu

@valentinedwv This is related to our discussion today I just tagged you in it.

I need this since when Nabu is running as a container launched by Portainer, it needs a more explicate path to the context files otherwise it's a bit of a mess (hard coded mess).  So just want to make this a config file entry.  The default should be set to just the schema.org context file in the same directory as the executable.  

https://github.com/gleanerio/nabu/blob/ce97e03918e53c46375de28603912f313b8c9f32/internal/graph/ldproc.go#LL39C2-L51C3

**Comment by valentinedwv** [comment]
Think this is already done with the bringing the dev up in sync with latest nabu
https://github.com/gleanerio/gleaner/pull/139
yes, slipped it in since does not effect gleaner, just the nabu called from glcon. 

or are you saying  you are going to add a config entry in nabu... in which case, go ahead ;)
in which case, dropping in assets works.... Even have a build step to get the latest. https://github.com/gleanerio/gleaner/blob/497980876769e42afda62a01c12a73b7a35c19ac/.github/workflows/release_gleaner.yml#L23
