### ISSUE TITLE
prune performance improvement

### ISSUE THREAD

**Issue by valentinedwv** [fils/nabu#44]
.   35 seconds  is on the test graph (now 70)
SELECT DISTINCT ?g WHERE {GRAPH ?g {?s ?p ?o} FILTER regex(str(?g), "^urn:test:geocodes_demo_datasets:")}
solutions=18, chunks=10, children=0, elapsed=342935ms, Cancel

https://graph.geocodes-aws-dev.earthcube.org/blazegraph/
test namespace

**Comment by fils** [comment]
So when I ran the above query it took 5+ minutes.

I rewrote it and the new version took..  15 minutes.   I'll class that a failure.  For record I tried the SPARQL CONTAINS rather than regex to see what was faster.  Seems obvious.  

It should be noted that just asking for the the distinct set of graphs took 18 seconds to collect 187K named graphs.  A bit of wire time to send that back, but still, that will be small.   This might be a case where the best approach is just to ask the graph for the named graph values and let the Go code do the rest.    ;) 

I'll work up an example tomorrow and test it and pass it along for you to look at.

**Comment by valentinedwv** [comment]
Get the feeling we are doing more over release files, or namespaces holding a single source

**Comment by fils** [comment]
agreed..  and there may be some approaches we can use there for this process.   However, might as well update this approach as well.

**Comment by valentinedwv** [comment]
`SELECT DISTINCT ?g WHERE {GRAPH ?g {} FILTER regex(str(?g), "^urn:test:geocodes_demo_datasets:")}`

think the explain on this is almost all 1

**Comment by fils** [comment]
wow..   I didn't even know you could do just a select on ?g.   I thought you had to have one triple pattern.  This is
great.  But why does

```
SELECT DISTINCT ?g WHERE {GRAPH ?g {} FILTER regex(str(?g), "^urn:test:geocodes_demo_datasets:")}
```
return 10182 results

and 


```
SELECT DISTINCT ?g WHERE {GRAPH ?g {?s ?p ?o} FILTER regex(str(?g), "^urn:test:geocodes_demo_datasets:")}
```

returns 63?   Obviously it's the distinct in the SPO, but not sure how that can be accounted for yet.

But not scanning SPO is way faster.  THANKS!  Should work perfect when just looking for the graph of a given JSON-LD data graph.

**Comment by valentinedwv** [comment]
test got deleted, and recreated... 
wait i see. yuck

**Comment by fils** [comment]
While 

```sparql
SELECT DISTINCT ?g WHERE {GRAPH ?g {} FILTER regex(str(?g), "iow")}
```
works in Blazegraph, it does not work in GraphDB.  It acts like there is no pattern to match and gives zero results.

will stick with the following for now (sadly) 

```sparql
SELECT DISTINCT ?g WHERE {GRAPH ?g {?s ?p ?o } FILTER regex(str(?g), "iow")}
```
